"""Build the two static front-ends from the one set of sources.

    docs/   offline, single-user  -> GitHub Pages. The workbook stays in the
            browser; no server, works with no internet once loaded.
    web/    shared, multi-user    -> Netlify. Talks to netlify/functions/api.mjs,
            which holds the workbook and syncs everyone.

Both render the same Jinja templates and copy the same CSS and UI JavaScript,
and the browser Excel engine in docs/ is generated from shared/engine-core.cjs -
the same module the Netlify function imports. Nothing is hand-maintained twice.

    python build_static.py
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOCS = ROOT / 'docs'
WEB = ROOT / 'web'
SHARED = ROOT / 'shared'

ENGINE_BOOTSTRAP = """
/* Bootstrap for the offline build: wire the shared core to the CDN copy of
   ExcelJS and the compiled schema. Generated by build_static.py. */
window.ParcelEngine = window.ParcelEngineFactory({
  schema: window.PARCEL_SCHEMA,
  ExcelJS: window.ExcelJS
});
"""


def render(app, template, **ctx):
    from flask import render_template
    with app.app_context():
        return render_template(template, **ctx)


def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def main():
    from app import create_app
    from app.routes import (FORM_ORDER, LABELS, REQUIRED_FIELDS, WIDE_FIELDS,
                            PROPERTY_TYPES, CHOICE_FIELDS, UI_CONFIG)

    app = create_app()
    schema = json.loads((SHARED / 'schema.json').read_text(encoding='utf-8'))
    for k in [k for k in schema if k.startswith('_')]:
        schema.pop(k)
    schema_js = ('/* GENERATED by build_static.py from shared/schema.json - do not edit. */\n'
                 'window.PARCEL_SCHEMA = ' + json.dumps(schema, indent=2) + ';\n')

    core = (SHARED / 'engine-core.cjs').read_text(encoding='utf-8')
    style = (ROOT / 'app' / 'static' / 'style.css').read_text(encoding='utf-8')
    app_js = (ROOT / 'app' / 'static' / 'app.js').read_text(encoding='utf-8')

    base = dict(fields=FORM_ORDER, labels=LABELS, required=REQUIRED_FIELDS,
                wide=WIDE_FIELDS, property_types=PROPERTY_TYPES, choices=CHOICE_FIELDS)

    # ---------------------------------------------------- docs/  (offline)
    DOCS.mkdir(exist_ok=True)
    write(DOCS / 'index.html', render(
        app, 'index.html', static_build=True, shared_build=False,
        ui_config=dict(UI_CONFIG, mode='local'), **base))
    write(DOCS / 'schema.js', schema_js)
    write(DOCS / 'style.css', style)
    write(DOCS / 'app.js', app_js)
    write(DOCS / 'engine.js', core + ENGINE_BOOTSTRAP)
    write(DOCS / '.nojekyll', '')

    # ----------------------------------------------------- web/  (shared)
    WEB.mkdir(exist_ok=True)
    shared_ui = dict(UI_CONFIG, mode='shared')
    write(WEB / 'index.html', render(
        app, 'index.html', static_build=True, shared_build=True,
        ui_config=shared_ui, **base))
    write(WEB / 'sheet.html', render(app, 'sheet.html', ui_config=shared_ui))
    write(WEB / 'style.css', style)
    write(WEB / 'app.js', app_js)
    write(WEB / 'shared.js', (ROOT / 'app' / 'static' / 'shared.js').read_text(encoding='utf-8'))
    write(WEB / 'sheet.js', (ROOT / 'app' / 'static' / 'sheet.js').read_text(encoding='utf-8'))

    for label, folder, names in [
        ('docs (offline, GitHub Pages)', DOCS,
         ['index.html', 'schema.js', 'style.css', 'app.js', 'engine.js']),
        ('web  (shared, Netlify)', WEB,
         ['index.html', 'sheet.html', 'style.css', 'app.js', 'shared.js', 'sheet.js']),
    ]:
        print(label)
        for n in names:
            p = folder / n
            print('   %-12s %7d bytes' % (n, p.stat().st_size if p.exists() else -1))


if __name__ == '__main__':
    main()
