"""Build the static, browser-only version of the app into docs/.

docs/ is what GitHub Pages serves. The build renders the same Jinja template
the Flask app uses and copies the same CSS and UI JavaScript, so the hosted
site and the local Flask app stay in step. The only file unique to the static
build is engine.js, which replaces the Flask API with ExcelJS in the browser.

    python build_static.py
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOCS = ROOT / 'docs'
SCHEMA_PATH = ROOT / 'shared' / 'schema.json'


def main():
    DOCS.mkdir(exist_ok=True)

    from app import create_app
    from app.routes import (FORM_ORDER, LABELS, REQUIRED_FIELDS, WIDE_FIELDS,
                            PROPERTY_TYPES, CHOICE_FIELDS, UI_CONFIG)

    app = create_app()
    with app.app_context():
        from flask import render_template
        html = render_template(
            'index.html',
            fields=FORM_ORDER, labels=LABELS, required=REQUIRED_FIELDS,
            wide=WIDE_FIELDS, property_types=PROPERTY_TYPES,
            choices=CHOICE_FIELDS, ui_config=UI_CONFIG,
            static_build=True,
        )
    (DOCS / 'index.html').write_text(html, encoding='utf-8')

    # Compile the shared schema into a plain global for the browser.
    schema = json.loads(SCHEMA_PATH.read_text(encoding='utf-8'))
    schema.pop('_comment', None)
    schema.pop('_header_map_comment', None)
    (DOCS / 'schema.js').write_text(
        '/* GENERATED by build_static.py from shared/schema.json - do not edit. */\n'
        'window.PARCEL_SCHEMA = ' + json.dumps(schema, indent=2) + ';\n',
        encoding='utf-8')

    shutil.copyfile(ROOT / 'app' / 'static' / 'style.css', DOCS / 'style.css')
    shutil.copyfile(ROOT / 'app' / 'static' / 'app.js', DOCS / 'app.js')

    # Stop GitHub Pages running the output through Jekyll.
    (DOCS / '.nojekyll').write_text('', encoding='utf-8')

    for f in ['index.html', 'schema.js', 'style.css', 'app.js', 'engine.js']:
        p = DOCS / f
        print('  %-12s %6d bytes' % (f, p.stat().st_size if p.exists() else -1))
    print('docs/ built')


if __name__ == '__main__':
    main()
